services:
  # Midnight Local Proof Server
  midnight-proof-server:
    image: midnightnetwork/proof-server:latest
    container_name: midnight-proof-server
    ports:
      - "6300:6300"  # Proof server port
      - "6301:6301"  # Metrics port
    environment:
      - PROOF_SERVER_PORT=6300
      - METRICS_PORT=6301
      - LOG_LEVEL=debug  # Enhanced logging for development
      - MAX_CIRCUIT_SIZE=4194304  # 4MB max circuit size (increased for SelectConnect)
      - CACHE_SIZE=2000  # Increased cache for better performance
      - WORKER_THREADS=8  # More threads for parallel proof generation
      - ENABLE_METRICS=true
      - PROOF_TIMEOUT=300  # 5 minutes timeout for complex proofs
    volumes:
      - ./contracts/build:/circuits  # Mount compiled circuits
      - midnight-proof-cache:/cache
    networks:
      - selectconnect-network
    command: ["midnight-proof-server", "--network", "testnet"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6301/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Midnight Local Node (for testing)
  midnight-node:
    image: midnightnetwork/midnight-node:0.12.1
    container_name: midnight-node
    ports:
      - "9944:9944"  # WebSocket RPC
      - "9933:9933"  # HTTP RPC
      - "30333:30333"  # P2P
    environment:
      - CHAIN=local
      - RPC_EXTERNAL=true
      - WS_EXTERNAL=true
      - RPC_CORS=all
      - PRUNING=archive
    volumes:
      - midnight-chain-data:/data
    networks:
      - selectconnect-network
    command: [
      "--dev",
      "--rpc-external",
      "--ws-external",
      "--rpc-cors=all",
      "--pruning=archive",
      "--base-path=/data"
    ]

  # Redis for Relay Service
  redis:
    image: redis:7.4-alpine
    container_name: selectconnect-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - selectconnect-network
    command: redis-server --appendonly yes --requirepass selectconnect_redis_2024
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bull Dashboard for Job Monitoring
  bull-board:
    image: deadly0/bull-board:latest
    container_name: selectconnect-bull-board
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=selectconnect_redis_2024
    depends_on:
      - redis
    networks:
      - selectconnect-network

  # Compact Circuit Compiler
  midnight-compiler:
    image: midnightnetwork/compactc:latest
    container_name: midnight-compiler
    volumes:
      - ./contracts:/workspace
      - ./contracts/build:/output
    working_dir: /workspace
    networks:
      - selectconnect-network
    profiles:
      - tools
    command: ["tail", "-f", "/dev/null"]  # Keep container running for manual compilation

  # Midnight Network Explorer (optional)
  midnight-explorer:
    image: nginx:alpine
    container_name: midnight-explorer
    ports:
      - "8080:80"
    volumes:
      - ./tools/explorer:/usr/share/nginx/html:ro
    networks:
      - selectconnect-network
    profiles:
      - tools

volumes:
  midnight-proof-cache:
  midnight-chain-data:
  redis-data:

networks:
  selectconnect-network:
    driver: bridge
